AppBundle\Entity\Task:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\TaskRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        taskName:
            type: string
            length: '255'
            column: task_name
        dueDate:
            type: datetime
    lifecycleCallbacks: {  }
