# src/AppBundle/Resources/config/admin.yml

services:
    admin.post:
        class: AppBundle\Admin\PostAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Post" }
        arguments:
            - ~
            - AppBundle\Entity\Post
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]
    admin.category:
        class: AppBundle\Admin\CategoryAdmin
        arguments: [~, AppBundle\Entity\Category, ~]
        tags:
           - { name: sonata.admin, manager_type: orm, group:"Content",  label: Category }